version: 2
sources:
   - name: raw
     schema: gz_raw_data
     tables:
       - name: sales
         identifier: raw_gz_sales
         description: sales of Greenweez / we have on row per product_id found in each orders_id
         columns:
           - name: date_date
           - name: orders_id
             description: An unique identifier for each order 
           - name: product_id
             description: an unique identifier for each category of product 
           - name: revenue 
           - name: quantity
         tests:
              - unique:
                 column_name: "(orders_id || '-' || pdt_id)"

           
       - name: product 
         identifier: raw_gz_product
         description: products sold by greenweez
         columns:
            - name: products_id
              description: an unique identifier for each category of product           
              tests:
               - unique
               - not_null
            - name: purchase_price
              description: An unique identifier for each order 
          
       - name: ship
         identifier:  raw_gz_ship 
         description: information regarding the prder's shipping of greenweez 
         columns:
            - name: orders_id
              description: an unique identifier for each order           
              tests:
               - unique
               - not_null
            - name: shipping_fee
            - name: shipping_fee_1
            - name: logcost 
            - name: ship_cost

       - name: adwords
         identifier:  raw_gz_adwords 
         columns:
            - name: date_date
            - name: paid_source
            - name: campaign_key
            - name: campaign_name 
            - name: ads_costs
            - name: impression
            - name: click
         tests:
              - unique:
                 column_name: "(date_date || '-' ||campaign_key)"

       - name: facebook
         identifier:  raw_gz_facebook
         columns:
            - name: date_date
            - name: paid_source
            - name: campaign_key
            - name: campaign_name 
            - name: ads_costs
            - name: impression
            - name: click
         tests:
              - unique:
                 column_name: "(date_date || '-' ||campaign_key)"



       - name: criteo
         identifier:  raw_gz_criteo
         columns:
            - name: date_date
            - name: paid_source
            - name: campaign_key
            - name: campaign_name 
            - name: ads_costs
            - name: impression
            - name: click
         tests:
              - unique:
                 column_name: "(date_date || '-' ||campaign_key)"


       - name: bing
         identifier:  raw_gz_bing
         columns:
            - name: date_date
            - name: paid_source
            - name: campaign_key
            - name: campaign_name 
            - name: ads_costs
            - name: impression
            - name: click
         tests:
              - unique:
                 column_name: "(date_date || '-' ||campaign_key)"
